import '@terra/styles/tailwind.css';
import 'node_modules/ol/ol.css';
import { Inter } from 'next/font/google';
import { Sidebar } from '@terra/components/interface/Navigations';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'TerraMap',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body style={inter.style} className="flex">
        <Sidebar />
        {children}
      </body>
    </html>
  );
}
